# Generated by Django 3.0.8 on 2020-07-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('authorized', models.BooleanField(default=False)),
                ('file', models.ImageField(upload_to='persons/')),
            ],
            options={
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('rtsp://admin:M14ercedes1@192.168.1.64:554>/Streaming/Channels/101/?tcp', 'Hikvision camera'), ('rtsp://192.168.1.62/user=admin&password=&channel=1&stream=0.sdp?real_stream', 'Gate camera'), ('http://192.168.1.65:8080/video', 'S7 Edge camera'), ('http://192.168.1.66:8080/video', 'A5 camera')], default='rtsp://192.168.1.62/user=admin&password=&channel=1&stream=0.sdp?real_stream', max_length=255)),
                ('crop', models.CharField(choices=[('1', '1'), ('0.75', '0.75'), ('0.5', '0.5'), ('0.25', '0.25'), ('0.125', '0.125')], default='0.25', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date of attempt to access')),
                ('granted', models.BooleanField(default=False)),
                ('snapshot', models.ImageField(blank=True, upload_to='snapshots/')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LiveView.Person')),
            ],
            options={
                'verbose_name_plural': 'logs',
            },
        ),
    ]
