# Generated by Django 3.0.8 on 2020-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='device',
            field=models.CharField(choices=[('rtsp://admin:M14ercedes1@192.168.1.64:554>/Streaming/Channels/101/?tcp', 'Hikvision camera'), ('rtsp://192.168.1.62/user=admin&password=&channel=1&stream=0.sdp?real_stream', 'Gate camera'), ('http://192.168.3.62:8080/video', 'S7 Edge camera'), ('http://192.168.3.63:8080/video', 'A5 camera')], default='rtsp://192.168.1.62/user=admin&password=&channel=1&stream=0.sdp?real_stream', max_length=255),
        ),
    ]
